## Previous Custom DL method for documentation
transferred to archive folder July 11

### Deep Learning Approaches for RF-based detection & classification

In [1]:
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random
import sys

# import the torch packages
from torch.nn import Module
from torch.nn import Conv2d
from torch.nn import Linear
from torch.nn import MaxPool2d
from torch.nn import ReLU
from torch.nn import LogSoftmax
from torch import flatten
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset

import torchvision.models as models

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

# import custom functions

# module_path = os.path.abspath(os.path.join('..'))
# if module_path not in sys.path:
#     sys.path.append(module_path)

# import RFClassification

import sys; sys.path.insert(0, '..') # add parent folder path where lib folder is
# import RFClassification.helper_functions # store_load is a file on my library folder
    
from helper_functions import *
from latency_helpers import *
from loading_functions import *

from sklearn import preprocessing

### Load Features

In [ ]:
feat_folder = '../Features/'
feat_name = 'SPEC'
seg_len = 200
# datestr = '2022-07-05'
n_per_seg = 512
interferences = ['CLEAN']
dataset = load_dronedetect_features(feat_folder, feat_name, seg_len, n_per_seg, interferences)

 70%|██████████████████████████████             | 56/80 [01:09<01:12,  3.03s/it]

In [3]:
print('dataset size', len(dataset))
print('shape of each item', dataset.__getitem__(10)[0].shape)

dataset size 948
shape of each item torch.Size([1, 257, 26785])


### 1. Custom NN

In [20]:
## Model settings
# Hyperparameters
batch_size = 8 # the number of samples processed before the model is updated. (number of samples in the training data)
num_classes = 7
learning_rate = 0.01
num_epochs = 100

# Device will determine whether to run the training on GPU or CPU.
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


In [26]:
# Creating a CNN class
class ConvNeuralNet(nn.Module):
    #  Determine what layers and their order in CNN object 
    def __init__(self, num_classes):
        super(ConvNeuralNet, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.avpool0 = nn.AvgPool2d(kernel_size=(50,200))
#         self.conv1 = nn.Conv2d(1, 8, 100)
#         self.avgpool1 = nn.AvgPool2d(kernel_size=3)
#         self.conv2 = nn.Conv2d(8, 8, 50)
#         self.conv3 = nn.Conv1d(64,128, 3)
#         self.conv4 = nn.Conv1d(128, 128, 3)
        self.dense = nn.Linear(1670, num_classes)
    
    # Progresses data across layers    
    def forward(self, x):
         # Max pooling over a (2, 2) window
        x = self.avpool0(x)
#         x = self.conv1(x)
#         x = self.avgpool1(x)
#         x = self.conv2(x)
#         x = self.avgpool1(x)
#         x = nn.Dropout(p=0.25)(x)
        x = torch.flatten(x,1)
        x = self.dense(x)
        return x

In [117]:
## Test a random input
# batch_size = 8
# input = torch.randn(batch_size, 1, 513, 13392)
# # input_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)

# net = ConvNeuralNet(7)
# out = net(input)
# print(input.shape)
# print(out.shape)

In [ ]:
## Set up Data
train_split_percentage = 0.7
split_lengths = [int(train_split_percentage*len(dataset)), len(dataset)-int(train_split_percentage*len(dataset))]
train_set, test_set = torch.utils.data.random_split(dataset, split_lengths)

train_loader = torch.utils.data.DataLoader(dataset = train_set,
                                           batch_size = batch_size,
                                           shuffle = True)


test_loader = torch.utils.data.DataLoader(dataset = test_set,
                                           batch_size = batch_size,
                                           shuffle = True)

In [28]:
model = ConvNeuralNet(num_classes)
model = model.to(device)

# Set Loss function with criterion
criterion = nn.CrossEntropyLoss()

# Set optimizer with optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate, weight_decay = 0.005, momentum = 0.9)  

total_step = len(train_loader)

In [29]:
# Training
# We use the pre-defined number of epochs to determine how many iterations to train the network on
for epoch in range(num_epochs):
    #Load in the data in batches using the train_loader object
    for i, (images, labels) in enumerate(train_loader): 
        labels = labels.type(torch.long)

        # Move tensors to the configured device
        images = images.to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    if epoch%10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))


In [32]:
loss.item()

1.822728157043457

In [31]:
## Check accuracy
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
#         images = images.repeat(1,3,1)
#         images = images.reshape(batch_size, 3, 1, 513)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        print(predicted)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    
    print('Accuracy of the network on the {} train images: {} %'.format(total, 100 * correct / total))


tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')
tensor([0, 0], device='cuda:0')
Accuracy of the network on the 114 train images: 17.54385964912281 %


In [119]:
labels

tensor([6., 2.], device='cuda:0')

### 2. Transfer learning from Resnet50 & Apply Logistic Regression (Swinney paper)

In [19]:
# use pretrained resnet feature and just keep up to the last layer
resnet50 = models.resnet50(pretrained=True)
modules=list(resnet50.children())[:-1]
# resnet50=nn.Sequential(*modules)
for p in resnet50.parameters():
    p.requires_grad = False

In [20]:
# test resnet
input = torch.randn(1,1,30,300)
inputr = input.repeat(1,3,1,1)
resnet50(inputr).shape

torch.Size([1, 1000])

In [21]:
resnet_feats = []
resnet_y = []
for n in range(len(dataset)):
    d = dataset.__getitem__(n)
    inarr = d[0]
    inputr = inarr.repeat(1,3,1,1)  # repeat to have 3 channels of the same info
    out = resnet50(inputr)
    resnet_feats.append(np.array(out))
    resnet_y.append(np.array(d[1]))

resnet_feats = np.array(resnet_feats)
resnet_y = np.array(resnet_y)

# flatten the middle dimension
resnet_feats = resnet_feats.reshape(resnet_feats.shape[0], resnet_feats.shape[-1])
# invert labels back to categorical
resnet_y_cat = dataset.le.inverse_transform(resnet_y.astype(np.int64))

In [86]:

# split data into K-fold
k_fold = 10
cv = KFold(n_splits=k_fold, random_state=1, shuffle=True)

# model parameters
Cs=list(map(lambda x:pow(2,x),range(-10,10,2)))

best_params_ls = []
acc_ls = []
f1_ls = []
runt_ls = []

parameters = {'C':Cs}

for train_ix, test_ix in cv.split(resnet_feats):
    
    # find the optimal hypber parameters
    lr = LogisticRegression(max_iter=10000)
    clf = GridSearchCV(lr, parameters, n_jobs=1)
    clf.fit(resnet_feats[train_ix], resnet_y_cat[train_ix])
    
    print(clf.best_params_)
    best_params_ls.append(clf.best_params_)
    
    # predict on the test data
    y_pred, runtimes = atomic_benchmark_estimator(clf, resnet_feats[test_ix], verbose=False)
    runt_ls.append(np.mean(runtimes))
    
    acc = accuracy_score(y_arr[test_ix], y_pred)
    f1 = f1_score(y_arr[test_ix], y_pred, average='weighted')
    print('Accuracy: {:.3},\t F1: {:.3}'.format(acc,f1))
    acc_ls.append(acc)
    f1_ls.append(f1)
    
out_msg = feat_name+': ResNet+LR average test acc: {:.2}, F1: {:.2}, Run-time: {:.2}ms'.format(np.mean(acc_ls), np.mean(f1_ls), np.mean(runt_ls)*1e3)
print(out_msg)

{'C': 64}
Accuracy: 0.974,	 F1: 0.974
{'C': 64}
Accuracy: 0.921,	 F1: 0.923
{'C': 256}
Accuracy: 0.921,	 F1: 0.925
{'C': 16}
Accuracy: 0.895,	 F1: 0.891
{'C': 16}
Accuracy: 0.921,	 F1: 0.92
{'C': 16}
Accuracy: 0.947,	 F1: 0.948
{'C': 64}
Accuracy: 1.0,	 F1: 1.0
{'C': 256}
Accuracy: 0.974,	 F1: 0.973
{'C': 256}
Accuracy: 0.921,	 F1: 0.924
{'C': 64}
Accuracy: 0.892,	 F1: 0.89
SPEC: ResNet+LR average test acc: 0.94, F1: 0.94, Run-time: 0.12ms


## 3. Apply resnet & a fully connected layer

In [87]:
resnet_feats.shape

(379, 1000)

In [96]:
# make a dataset out of resnet features
class ResNetFeatData(Dataset): ## NUMBERICAL DATA
    def __init__(self, Xarr, yarr):
        self.Xarr = Xarr
        test_list=[]
        self.le = preprocessing.LabelEncoder()
        self.le.fit(yarr.flatten())
        self.yarr = le.transform(yarr.flatten())
        
    def __len__(self):
        return len(self.yarr)
    
    def __getitem__(self, index):
        # all data must be in float and tensor format
        X = torch.tensor((self.Xarr[index]))
        X = X.unsqueeze(0)
        y = torch.tensor(float(self.yarr[index]))
        return (X, y)

In [97]:
resdataset = ResNetFeatData(resnet_feats, y_arr)

In [5]:
## Network for fully connected layer
class FCNet(nn.Module):
    def __init__(self, num_classes):
        super(FCNet, self).__init__()
        self.fc_layer = nn.Linear(1000, num_classes)
    
    # Progresses data across layers    
    def forward(self, x):
        x = self.fc_layer(x)
        return x


In [126]:
# Configuration options
k_folds = 10
num_epochs = 10
batch_size = 8
loss_function = nn.CrossEntropyLoss()

# For fold results
results = {}

# Define the K-fold Cross Validator
kfold = KFold(n_splits=k_folds, shuffle=True)

# Start print
print('--------------------------------')

# K-fold Cross Validation model evaluation
for fold, (train_ids, test_ids) in enumerate(kfold.split(resdataset)):
    # Print
    print(f'FOLD {fold}')
    print('--------------------------------')

    # Sample elements randomly from a given list of ids, no replacement.
    train_subsampler = torch.utils.data.SubsetRandomSampler(train_ids)
    test_subsampler = torch.utils.data.SubsetRandomSampler(test_ids)

    # Define data loaders for training and testing data in this fold
    trainloader = torch.utils.data.DataLoader(
                      resdataset, 
                      batch_size=batch_size, sampler=train_subsampler)
    testloader = torch.utils.data.DataLoader(
                      resdataset,
                      batch_size=batch_size, sampler=test_subsampler)

    # Init the neural network
    network = FCNet(7)
#     network.apply(reset_weights)

    # Initialize optimizer
    optimizer = torch.optim.Adam(fc_layer.parameters(), lr=1e-4)

    # Run the training loop for defined number of epochs
    for epoch in range(0, num_epochs):
        # Print epoch
        print(f'Starting epoch {epoch+1}')

        # Set current loss value
        current_loss = 0.0

        # Iterate over the DataLoader for training data
        for i, data in enumerate(trainloader, 0):
            # Get inputs
            inputs, targets = data

            # Zero the gradients
            optimizer.zero_grad()

            # Perform forward pass
            outputs = network(inputs)

            # Compute loss
            _, predicted = torch.max(outputs.data, 1)
            targets= targets.type(torch.long)
            loss = loss_function(predicted, targets)

            # Perform backward pass
            loss.backward()

            # Perform optimization
            optimizer.step()

            # Print statistics
            current_loss += loss.item()
            if i % 500 == 499:
                print('Loss after mini-batch %5d: %.3f' %
                      (i + 1, current_loss / 500))
                current_loss = 0.0

    # Process is complete.
    print('Training process has finished. Saving trained model.')

    # Print about testing
    print('Starting testing')

    # Saving the model
#     save_path = f'./model-fold-{fold}.pth'
#     torch.save(network.state_dict(), save_path)

    # Evaluationfor this fold
    correct, total = 0, 0
    with torch.no_grad():

        # Iterate over the test data and generate predictions
        for i, data in enumerate(testloader, 0):
            # Get inputs
            inputs, targets = data

            # Generate outputs
            outputs = fc_layer(inputs)

            # Set total and correct
            _, predicted = torch.max(outputs.data, 1)
            total += targets.size(0)
            correct += (predicted == targets).sum().item()

            # Print accuracy
            print('Accuracy for fold %d: %d %%' % (fold, 100.0 * correct / total))
    print('--------------------------------')
    results[fold] = 100.0 * (correct / total)

# Print fold results
print(f'K-FOLD CROSS VALIDATION RESULTS FOR {k_folds} FOLDS')
print('--------------------------------')
sum = 0.0
for key, value in results.items():
    print(f'Fold {key}: {value} %')
    sum += value
print(f'Average: {sum/len(results.items())} %')

--------------------------------
FOLD 0
--------------------------------


TypeError: super(type, obj): obj must be an instance or subtype of type

In [121]:
targets.shape

torch.Size([8])